---
spring:
  config.activate.on-profile: default
  datasource:
    url: 'jdbc:sqlite:/Users/rupamchakraborty/Desktop/Code/Practics/CDS/project1/sample-api/db.sqlite'
    driver-class-name: org.sqlite.JDBC
cds:
  odata-v4.endpoint.path: '/api'
  data-source.auto-config.enabled: false
